### PR TITLE
(SIMP-6921) Support puppetlabs/stdlib 6.x and puppet 6.x.

### PR DESCRIPTION
**Pull request by pillarsdotnet**
- Drop Puppet 4 support
- Add Puppet 6 support
- Add puppetlabs-stdlib 6 support

SIMP-6909 #comment pupmod-simp-simp_gitlab
SIMP-6934 #comment pupmod-simp-simp_gitlab

### CODE REVIEW

**Comment by lnemsick-simp** [comment]
This major version bump of puppet-gitlab (3.x -> 4.x) needs to be assessed carefully.  simp-simp_gitlab has logic that is highly coupled to the internals of puppet-gitlab in order to work around security defects (such as the GitLab root password not being set by default).  It is likely to require manifest changes that are not backward compatible with puppet-gitlab 3.x.

**Comment by pillarsdotnet** [comment]
Moved the gitlab version bump to a separate ticket and PR.

**Comment by lnemsick-simp** [comment]
:heavy_check_mark: https://gitlab.com/simp/pupmod-simp-simp_gitlab/pipelines/76406443

**Comment by lnemsick-simp** [comment]
:heavy_check_mark: https://gitlab.com/simp/pupmod-simp-simp_gitlab/pipelines/76406443

**Pull request merged**
